"""add audit_events table

Revision ID: 1353ecd6edb2
Revises: 7bb5211c522b
Create Date: 2026-01-12 02:01:18.466748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1353ecd6edb2'
down_revision: Union[str, None] = '7bb5211c522b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
